# This file should only be edited from the template
name: main

on:
  push:
    branches:
      - '**/issue**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: read
  issues: write

jobs:
  build:
    name: mainline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  echo ${{ github.sha }} | cut -c -7
      
